### ISSUE TITLE
ionic serve error

### ISSUE THREAD

**Issue by RunningV** [aaronchen2k/mobistore#4]
there is nothing error when i run 'npm install', all seems install seccess,only some warns
i searched on the github about the likely issue (https://github.com/driftyco/ionic-cli/issues/875)
but i can't solve it ,pls help me, tks

<pre>Error: ENOENT: no such file or directory, lstat 'E:\Running\angular2.0\ionic2\mobistore-client-master\typings\main.d.ts'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at Object.realpathSync (fs.js:1439:21)
    at E:\Running\angular2.0\ionic2\mobistore-client-master\node_modules\tsify\index.js:58:38
    at Array.map (native)
    at DestroyableTransform.flush [as _flush] (E:\Running\angular2.0\ionic2\mobistore-client-master\node_modules\tsify\index.js:58:6)
    at DestroyableTransform.<anonymous> (E:\Running\angular2.0\ionic2\mobistore-client-master\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
</pre>

My system information:

<pre>
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Windows 7 SP1
Node Version: v4.4.0
</pre>

**Comment by aaronchen2k** [comment]
follow this to setup 
http://ionicframework.com/docs/v2/getting-started/installation/

**Comment by RunningV** [comment]
u didn't look my problem carefully

<pre> no such file or directory, lstat 'E:\Running\angular2.0\ionic2\mobistore-client-master\typings\main.d.ts'</pre>

i don't think it's the environment fault,i have my own ionic2 project runs ok.
i will be grateful to u if u can solve my problem, tsk

**Comment by aaronchen2k** [comment]
I have a typings forder in project with main.d.ts in it, please try to receate an ionic2.0 project and copy to it.
